function customizedFigureOpen
figure;
set (gcf, 'DefaultTextFontName', 'Verdana', ...
    'DefaultTextFontSize', 10, ...
    'DefaultAxesFontName', 'Verdana', ...
    'DefaultAxesFontSize', 8, ...
    'DefaultLineMarkerSize', 9);
end